### ISSUE TITLE
Update Outreachy Round details

### ISSUE THREAD

**Issue by pavithraes** [QEDK/goodbot#48]
Bot config needs to be updated to point to Round 21 pages. :)

**Comment by QEDK** [comment]
Fixed related bug in 214dcac

**Comment by QEDK** [comment]
@pavithraes since the page doesn't have any content, parsebot will make a commit with an empty list, which is not that useful. I think it's better to use the bot's config module to change and commit it once the page has been updated (I fixed it right now, ping me if it breaks!)

**Comment by pavithraes** [comment]
Sounds good, thank you!
